name: my_fashion_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.1.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  cached_network_image: ^3.1.0
  path_provider: ^2.1.5
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/underc.png
    - assets/mobile.png
    - assets/aa.png
    - assets/bb.png
    - assets/cc.png
    - assets/dd.png
    - assets/ee.png
    - assets/ff.png
    - assets/gg.png
    - assets/hh.png
    - assets/aaa.png
    - assets/bbb.png
    - assets/ccc.png
    - assets/ddd.png
    - assets/eee.png
    - assets/fff.png
    - assets/ggg.png
    - assets/hhh.png
    - assets/back.png
    - assets/backk.png
    - assets/backkk.png
    - assets/backkkk.png
    - assets/backkkkk.png
    - assets/icon.png
    - assets/login.png
    - assets/draw.png
    - assets/apple.png
    - assets/google.png
    - assets/ig.png
    - assets/facebook.png
    - assets/backc.png
    - assets/baby_onesie.png
    - assets/baby_hat.png
    - assets/baby_jacket.png
    - assets/baby_mittens_socks.png
    - assets/baby_romper.png
    - assets/baby_sleepwear.png
    - assets/baby_pants.png
    - assets/baby_hooded_towel.png
    - assets/baby_cardigan.png
    - assets/baby_footed_pajamas.png
    - assets/baby_jacket_fur.png
    - assets/baby_gloves.png
    - assets/baby_summer_dress.png
    - assets/baby_romper_set.png
    - assets/baby_sweatshirt.png
    - assets/baby_winter_coat.png
    - assets/baby_sun_hat.png
    - assets/baby_pajamas.png
    - assets/baby_skirt.png
    - assets/baby_swimwear.png
    - assets/baby_snowsuit.png
    - assets/baby_tights.png
    - assets/baby_bibs.png
    - assets/baby_jacket_hood.png
    - assets/baby_booties.png
    - assets/baby_shoes.png
    - assets/baby_leggings.png
    - assets/baby_sweater.png
    - assets/baby_denim_shorts.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
