import 'package:my_fashion_app/models/product.dart';

class ProductService {
  Future<List<Product>> getProducts() async {
    // simulate API request delay
    await Future.delayed(Duration(seconds: 2));

    return [
      Product(
        id: 1,
        price: 45,
        title: 'Baby Sweater',
        image: 'assets/baby_sweater.png',
        description: 'Soft and warm baby sweater, perfect for cold weather.',
        gender: 'unisex',
      ),
      Product(
        id: 2,
        price: 30,
        title: 'Baby Shoes',
        image: 'assets/baby_shoes.png',
        description: 'Comfortable and stylish baby shoes for little feet.',
        gender: 'unisex',
      ),
      Product(
        id: 3,
        price: 20,
        title: 'Baby Onesie',
        image: 'assets/baby_onesie.png',
        description:
            'Cotton onesie for newborns and infants, gentle on the skin.',
        gender: 'unisex',
      ),
      Product(
        id: 4,
        price: 25,
        title: 'Baby Hat',
        image: 'assets/baby_hat.png',
        description: 'Soft knitted baby hat to keep little heads warm.',
        gender: 'unisex',
      ),
      Product(
        id: 5,
        price: 35,
        title: 'Baby Jacket',
        image: 'assets/baby_jacket.png',
        description:
            'A cozy and stylish jacket to keep your baby warm and comfy.',
        gender: 'unisex',
      ),
      Product(
        id: 6,
        price: 15,
        title: 'Baby Mittens & Socks Set',
        image: 'assets/baby_mittens_socks.png',
        description:
            'A set of baby mittens and socks to keep tiny hands and feet warm.',
        gender: 'unisex',
      ),
      Product(
        id: 7,
        price: 40,
        title: 'Baby Romper',
        image: 'assets/baby_romper.png',
        description: 'Cute and breathable baby romper, perfect for playtime.',
        gender: 'unisex',
      ),
      Product(
        id: 8,
        price: 50,
        title: 'Baby Sleepwear Set',
        image: 'assets/baby_sleepwear.png',
        description:
            'Soft, breathable sleepwear set for a peaceful night’s sleep.',
        gender: 'unisex',
      ),
      Product(
        id: 9,
        price: 28,
        title: 'Baby Pants',
        image: 'assets/baby_pants.png',
        description: 'Comfortable pants for everyday wear.',
        gender: 'unisex',
      ),
      Product(
        id: 10,
        price: 55,
        title: 'Baby Hooded Towel',
        image: 'assets/baby_hooded_towel.png',
        description: 'Cute and absorbent hooded towel for after bath time.',
        gender: 'unisex',
      ),
      Product(
        id: 11,
        price: 40,
        title: 'Baby Cardigan',
        image: 'assets/baby_cardigan.png',
        description: 'Stylish baby cardigan for layering in cool weather.',
        gender: 'unisex',
      ),
      Product(
        id: 12,
        price: 65,
        title: 'Baby Footed Pajamas',
        image: 'assets/baby_footed_pajamas.png',
        description: 'Cozy and warm footed pajamas for your baby’s comfort.',
        gender: 'unisex',
      ),
      Product(
        id: 13,
        price: 70,
        title: 'Baby Jacket with Fur',
        image: 'assets/baby_jacket_fur.png',
        description: 'Cute and warm jacket with faux fur lining.',
        gender: 'unisex',
      ),
      Product(
        id: 14,
        price: 18,
        title: 'Baby Gloves Set',
        image: 'assets/baby_gloves.png',
        description: 'Gentle and soft gloves for baby’s tiny hands.',
        gender: 'unisex',
      ),
      Product(
        id: 15,
        price: 30,
        title: 'Baby Leggings',
        image: 'assets/baby_leggings.png',
        description: 'Soft and stretchy leggings for your baby to move freely.',
        gender: 'unisex',
      ),
      Product(
        id: 16,
        price: 50,
        title: 'Baby Summer Dress',
        image: 'assets/baby_summer_dress.png',
        description: 'Lightweight summer dress for a cool, breezy look.',
        gender: 'female',
      ),
      Product(
        id: 17,
        price: 45,
        title: 'Baby Denim Shorts',
        image: 'assets/baby_denim_shorts.png',
        description: 'Stylish denim shorts for summer fun.',
        gender: 'unisex',
      ),
      Product(
        id: 18,
        price: 35,
        title: 'Baby Romper Set',
        image: 'assets/baby_romper_set.png',
        description: 'A set of adorable rompers for various occasions.',
        gender: 'unisex',
      ),
      Product(
        id: 19,
        price: 40,
        title: 'Baby Sweatshirt',
        image: 'assets/baby_sweatshirt.png',
        description: 'Warm and cozy sweatshirt for cool days.',
        gender: 'unisex',
      ),
      Product(
        id: 20,
        price: 60,
        title: 'Baby Winter Coat',
        image: 'assets/baby_winter_coat.png',
        description: 'A warm and stylish coat for the winter season.',
        gender: 'unisex',
      ),
      Product(
        id: 21,
        price: 25,
        title: 'Baby Sun Hat',
        image: 'assets/baby_sun_hat.png',
        description: 'Protect your baby from the sun with this cute sun hat.',
        gender: 'unisex',
      ),
      Product(
        id: 22,
        price: 20,
        title: 'Baby Pajamas Set',
        image: 'assets/baby_pajamas.png',
        description: 'Comfortable and soft pajamas for a restful night.',
        gender: 'unisex',
      ),
      Product(
        id: 23,
        price: 30,
        title: 'Baby Skirt',
        image: 'assets/baby_skirt.png',
        description: 'Cute and breathable skirt for baby girls.',
        gender: 'female',
      ),
      Product(
        id: 24,
        price: 65,
        title: 'Baby Swimwear Set',
        image: 'assets/baby_swimwear.png',
        description: 'Perfect swimwear for your baby’s first splash!',
        gender: 'unisex',
      ),
      Product(
        id: 25,
        price: 40,
        title: 'Baby Snowsuit',
        image: 'assets/baby_snowsuit.png',
        description: 'Warm and cozy snowsuit for cold weather.',
        gender: 'unisex',
      ),
      Product(
        id: 26,
        price: 50,
        title: 'Baby Tights',
        image: 'assets/baby_tights.png',
        description: 'Soft and stretchy tights for comfort and warmth.',
        gender: 'unisex',
      ),
      Product(
        id: 27,
        price: 22,
        title: 'Baby Bandana Bibs Set',
        image: 'assets/baby_bibs.png',
        description: 'Set of stylish and absorbent bibs for feeding time.',
        gender: 'unisex',
      ),
      Product(
        id: 28,
        price: 25,
        title: 'Baby Jacket with Hood',
        image: 'assets/baby_jacket_hood.png',
        description:
            'Stylish baby jacket with a built-in hood for extra warmth.',
        gender: 'unisex',
      ),
      Product(
        id: 29,
        price: 15,
        title: 'Baby Booties',
        image: 'assets/baby_booties.png',
        description: 'Soft and cute baby booties for tiny feet.',
        gender: 'unisex',
      ),
    ];
  }
}
